### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by dllen** [airforce-captain/docker#1]
mysql密码怎么设置？谢谢

**Comment by airforce-captain** [comment]
哪一个mysql密码设置？

任何一个使用 mysql 镜像都可以根据mysql官方指导，在使用docker run 命令中增加变量名设置如: 

-e MYSQL_ROOT_PASSWORD=you_password

**Comment by dllen** [comment]
不好意思没有说明白，walle的哪个镜像。

**Comment by airforce-captain** [comment]
噢，walle 那个镜像默认的mysql  root 是空密码的，但是此root 默认不允许外部连接的，不用担心。需要从镜像里连接才可以。为了减小镜像体积，未包含mysql 客户端，请自行安装一下。

以交互模式进入容器:
```
docker exec -it  Walle_container_id '/bin/sh'
```
安装mysql客户端：
```
apk --no-cache add mariadb-client
```
最后可以使用mysql客户端mysqladmin 或者登录数据库修改root的访问权限以及密码了。
